=== Briy1t/DAM/lenguaje-de-marca/facturas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:c="http://www.facturas.com/facturas"
    targetNamespace="http://www.facturas.com/facturas"
    elementFormDefault="qualified">

    <xs:element name="facturas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="factura" minOccurs="2" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fecha_emision" type="xs:date" />
                            <xs:element name="empresa_emisora" type="xs:string" />
                            <xs:element name="importe_total">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minInclusive value="0" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="iva">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minInclusive value="0" />
                                        <xs:maxInclusive value="100" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id_factura" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="FAC-[0-9]{5}" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                        <xs:attribute name="metodo_pago" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="efectivo" />
                                <xs:enumeration value="tarjeta" />
                                <xs:enumeration value="transferencia" />
                            </xs:restriction>
                        </xs:simpleType>
                        </xs:attribute>

                        <xs:attribute name="pagado" type="xs:boolean" use="optional" default="false" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Briy1t/DAM/lenguaje-de-marca/facturas.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:facturas xmlns:c="http://www.facturas.com/facturas"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.facturas.com/facturas facturas.xsd">

        <c:factura id_factura="FAC-00012" metodo_pago="tarjeta" pagado="false">
            <c:fecha_emision>2026-06-15</c:fecha_emision>
            <c:empresa_emisora>Cooporación S.A.</c:empresa_emisora>
            <c:importe_total>100</c:importe_total>
            <c:iva>21</c:iva>
        </c:factura>

        <c:factura id_factura="FAC-00013" metodo_pago="efectivo" pagado="true">
            <c:fecha_emision>2026-07-18</c:fecha_emision>
            <c:empresa_emisora>Operative</c:empresa_emisora>
            <c:importe_total>200</c:importe_total>
            <c:iva>24</c:iva>
        </c:factura>

        <c:factura id_factura="FAC-00014" metodo_pago="transferencia" pagado="false">
            <c:fecha_emision>2026-08-20</c:fecha_emision>
            <c:empresa_emisora>Integración S.A.</c:empresa_emisora>
            <c:importe_total>150</c:importe_total>
            <c:iva>18</c:iva>
        </c:factura>
        
</c:facturas>
