=== Briy1t/DAM/lenguaje-de-marca/menu.dtd
<!ELEMENT menu (entrantes, platos_principales, postres)>
<!ELEMENT entrantes (plato+)>
<!ELEMENT platos_principales (plato+)>
<!ELEMENT postres (plato+)>
<!ELEMENT plato (nombre, descripcion? , precio, alergeno*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT precio (#PCDATA )>
<!ELEMENT alergeno (#PCDATA)>
<!ATTLIST plato codigo ID #REQUIRED>
<!ATTLIST plato vegetariano (si) #IMPLIED>
<!ATTLIST precio moneda CDATA #IMPLIED >

=== Briy1t/DAM/lenguaje-de-marca/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "menu.dtd">
<menu>
    <entrantes>
        <plato codigo="E01" vegetariano="si">
            <nombre>Ensalada de pollo</nombre>
            <descripcion>Ensalada de Tofú con ingredientes frescos y aderezo especial</descripcion>
            <precio moneda="€">8.99</precio>
            <alergeno>frutos secos</alergeno>
            <alergeno>lactosa</alergeno>
        </plato>
        <plato codigo="E02" vegetariano="si">
            <nombre>Sopa de verduras</nombre>
            <descripcion>Sopa de verduras con ingredientes frescos</descripcion>
            <precio moneda="€">4.99</precio>
        </plato>
    </entrantes>
    <platos_principales>
        <plato codigo="P01" >
            <nombre>Pollo al horno</nombre>
            <descripcion>Pollo al horno con especias y salsa de la casa</descripcion>
            <precio moneda="€">12.98</precio>
            <alergeno>gluten</alergeno>
            <alergeno>lactosa</alergeno>
        </plato>
        <plato codigo="P02" vegetariano="si">
            <nombre>Ensalada de quinoa</nombre>
            <descripcion>Ensalada de quinoa con vegetales y aderezo especial</descripcion>
            <precio moneda="€">10.99</precio>
        </plato>
    </platos_principales>
    <postres>
        <plato codigo="B01" vegetariano="si">
            <nombre>Flan</nombre>
            <descripcion>Flan casero con caramelo</descripcion>
            <precio moneda="€">5.99</precio>
            <alergeno>huevos</alergeno>
            <alergeno>lactosa</alergeno>
        </plato>
        <plato codigo="B02" >
            <nombre>Helado de vainilla</nombre>
            <descripcion>Helado de vainilla con trozos de chocolate y galleta</descripcion>
            <precio moneda="€">4.99</precio>
            <alergeno>gluten</alergeno>
            <alergeno>lactosa</alergeno>
        </plato>
    </postres>
 
</menu>
