=== Briy1t/DAM/congreso.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.congreso.com/schema"
    xmlns:c="http://www.congreso.com/schema"
    elementFormDefault="qualified">
    <xs:element name="congreso">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ponentes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ponente" minOccurs="2" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="organizacion" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="id" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="P[0-9]{2}" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="charlas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="charla" minOccurs="3" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titulo" type="xs:string" />
                                        <xs:element name="resumen" type="xs:string" />
                                        <xs:element name="sala" type="xs:string" />                                   
                                    </xs:sequence>
                                    <xs:attribute name="ponente_ref" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>

        <xs:key name="ponente-key">
            <xs:selector xpath=".//c:ponente" />
            <xs:field xpath="@id" />
        </xs:key>

        <xs:keyref name="charla-ponente-ref" refer="c:ponente-key">
            <xs:selector xpath=".//c:charla" />
            <xs:field xpath="@ponente_ref" />
        </xs:keyref>

    </xs:element>
</xs:schema>

=== Briy1t/DAM/congreso.xml
<?xml version="1.0" encoding="UTF-8"?>
<cong:congreso xmlns:cong="http://www.congreso.com/schema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.congreso.com/schema congreso.xsd">

    <cong:ponentes>
        <cong:ponente id="P01">
            <cong:nombre>Juan Pérez</cong:nombre>
            <cong:organizacion>Universidad de la Ciudad</cong:organizacion>
        </cong:ponente> 

        <cong:ponente id="P02">
            <cong:nombre>María García</cong:nombre>
            <cong:organizacion>Universidad Nacional</cong:organizacion>
        </cong:ponente> 

        <cong:ponente id="P03">
            <cong:nombre>Andrés Rojas</cong:nombre>
            <cong:organizacion>Universidad Tecnológica</cong:organizacion>
        </cong:ponente> 
    </cong:ponentes>

    <cong:charlas >
        <cong:charla ponente_ref="P02">
            <cong:titulo>La inteligencia artificial y su impacto en la sociedad</cong:titulo>
            <cong:resumen>Exploraremos cómo la inteligencia artificial está transformando diversos aspectos de nuestra vida cotidiana y su influencia en la sociedad.</cong:resumen>
            <cong:sala>Sala A</cong:sala>
        </cong:charla>
        <cong:charla ponente_ref="P03">
            <cong:titulo>La innovación tecnológica en la educación</cong:titulo>
            <cong:resumen>Analizaremos cómo las nuevas tecnologías están revolucionando el entorno educativo y mejorando la experiencia del alumno.</cong:resumen>
            <cong:sala>Sala B</cong:sala>
        </cong:charla>
        <cong:charla ponente_ref="P01">
            <cong:titulo>La gestión del cambio en organizaciones</cong:titulo>
            <cong:resumen>Estudiaremos las estrategias efectivas para gestionar el cambio en entornos organizacionales dinámicos.</cong:resumen>
            <cong:sala>Sala C</cong:sala>
        </cong:charla>
        <cong:charla ponente_ref="P02">
            <cong:titulo>Las tendencias en el desarrollo de software</cong:titulo>
            <cong:resumen>Analizaremos las últimas tendencias en el desarrollo de software y su impacto en la industria.</cong:resumen>
            <cong:sala>Sala D</cong:sala>
        </cong:charla>
    </cong:charlas>
</cong:congreso>
